Repository naturalcrit/homebrewery, pull requests merged in 2021-09, with the labels that each got.

#1680 [v3] Better Paragraph formatting in Monster blocks
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/editor/snippetbar/snippets/monsterblock.gen.js
  client/homebrew/editor/snippetbar/snippets/tableOfContents.gen.js
  themes/5ePhb.style.less
Labels: ⚠️ Broken in V3

#1693 Add `.pages` container div to printPage.jsx
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/pages/printPage/printPage.jsx
Labels: bug-regression

#1586 Update editor.less for .pageLine
  client/homebrew/editor/editor.less
Labels: tweak, UI/UX
