Repository naturalcrit/homebrewery, pull requests merged in 2021-12, with the labels that each got.

#1568 Hotkey for hyperlinks (`Ctrl`/`Cmd` + `K`)
  shared/naturalcrit/codeEditor/codeEditor.jsx
Labels: UI/UX, P3 - low priority

#1645 Add Hotkeys for Underline and makeDiv
  shared/naturalcrit/codeEditor/codeEditor.jsx
Labels: P3 - low priority

#1707 Added heading shortcuts (H1 to H6)
  shared/naturalcrit/codeEditor/codeEditor.jsx
Labels: P3 - low priority

#1719 Hotkey for Lists
  shared/naturalcrit/codeEditor/codeEditor.jsx
Labels: P3 - low priority

#1809 Page numbers via js
  client/homebrew/editor/editor.jsx
  client/homebrew/editor/editor.less
Labels: P1 - high priority

#1874 Tell CodeMirror to batch custom highlights before updating the browser
  client/homebrew/editor/editor.jsx
Labels: P1 - high priority

#1841 Adding metadata block to brew text for Google brews
  config/default.json
  package-lock.json
  package.json
  server.js
  server/homebrew.api.js
Labels: P1 - high priority

#1759 Fix text wrapping in code blocks
  themes/5ePhb.style.less
Labels: P2 - minor feature or not urgent

#1901 Add Install Instructions - Ubuntu
  install/README.FREEBSD.md
  install/README.UBUNTU.md
  install/freebsd/install.sh
  install/freebsd/rc.d/homebrewery
  install/ubuntu/etc/systemd/system/homebrewery.service
  install/ubuntu/install.sh
Labels: tweak, P3 - low priority
