Repository naturalcrit/homebrewery, pull requests merged in 2022-02, with the labels that each got.

#1897 Legacy -> v3 Migration guide
  client/homebrew/navbar/help.navitem.jsx
  client/homebrew/navbar/issue.navitem.jsx
  client/homebrew/navbar/navbar.less
  client/homebrew/navbar/recent.navitem.jsx
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/errorPage/errorPage.jsx
  client/homebrew/pages/homePage/homePage.jsx
  client/homebrew/pages/homePage/migrate.md
  client/homebrew/pages/newPage/newPage.jsx
  client/homebrew/pages/userPage/userPage.jsx
  server/app.js
  shared/naturalcrit/nav/nav.less
  shared/naturalcrit/styles/colors.less
Labels: P2 - minor feature or not urgent, Reviewed - Awaiting Fixes

#1799 Create Base Page structure - ListPage
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.less
  client/homebrew/pages/basePages/listPage/listPage.jsx
  client/homebrew/pages/basePages/listPage/listPage.less
  client/homebrew/pages/userPage/userPage.jsx
Labels: P2 - minor feature or not urgent, Reviewed - Awaiting Fixes

#2007 Make brewItems stand out a bit.
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.less
Labels: tweak, UI/UX, P3 - low priority

#2015 Add logout button
  client/homebrew/navbar/account.navitem.jsx
  client/homebrew/navbar/navbar.less
Labels: P1 - high priority, Approved
