Repository naturalcrit/homebrewery, pull requests merged in 2022-11, with the labels that each got.

#2479 [AccountPage] Modify query to exclude Google brew stubs
  server/app.js
Labels: P1 - high priority

#2453 Change `<meta>` tags based on Current Page
  client/template.js
  server/app.js
Labels: UI/UX

#2499 Fix template.js crash when ogMeta undefined
  client/template.js
Labels: P0 - security or data loss

#2442 Add Ability to Remove Brews from Recent Items
  client/homebrew/navbar/navbar.less
  client/homebrew/navbar/recent.navitem.jsx
Labels: UI/UX, P2 - minor feature or not urgent

#2506 Add link to FAQ in "Need Help" menu
  client/homebrew/navbar/help.navitem.jsx
Labels: UI/UX

#2503 Add syntax highlighting for injections
  client/homebrew/editor/editor.jsx
  client/homebrew/editor/editor.less
Labels: UI/UX

#2488 Field validation system 2
  client/homebrew/editor/metadataEditor/metadataEditor.jsx
  client/homebrew/editor/metadataEditor/metadataEditor.less
  client/homebrew/editor/metadataEditor/validations.js
Labels: UI/UX, Reviewed - Needs Help

#2507 Move common meta tags to default object
  server/app.js
Labels: cleanup

#2517 Update Style for V3 & Legacy
  themes/Legacy/5ePHB/style.less
  themes/V3/Blank/style.less
Labels: P1 - high priority
