Repository naturalcrit/homebrewery, pull requests merged in 2022-06, with the labels that each got.

#2162 Brew & Source Navigation
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/editor/editor.jsx
  scripts/project.json
  shared/naturalcrit/codeEditor/codeEditor.jsx
  shared/naturalcrit/codeEditor/codeEditor.less
  shared/naturalcrit/splitPane/splitPane.jsx
  shared/naturalcrit/splitPane/splitPane.less
Labels: P1 - high priority, Reviewed - Awaiting Fixes

#2211 Fix Overlapping ClassTable Decorations
  themes/5ePhb.style.less
Labels: P1 - high priority, Approved

#2114 Google Drive document stubs
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/newPage/newPage.jsx
  client/homebrew/pages/sharePage/sharePage.jsx
  server/app.js
  server/googleActions.js
  server/homebrew.api.js
  server/homebrew.model.js
Labels: feature, P1 - high priority

#1699 Allow wide classTables to bleed into top margin
  themes/5ePhb.style.less
Labels: P2 - minor feature or not urgent
