Repository naturalcrit/homebrewery, pull requests merged in 2022-10, with the labels that each got.

#2384 Add ability to toggle the Auto Save
  client/homebrew/navbar/navbar.less
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/editPage/editPage.less
Labels: UI/UX, Reviewed - Awaiting Fixes

#2392 [Editor] Prevent unfolding code in Editor when adding a Snippet
  client/homebrew/editor/editor.jsx
  shared/naturalcrit/codeEditor/codeEditor.jsx
Labels: P2 - minor feature or not urgent, Reviewed - Awaiting Fixes

#2425 Add URI encoding to User Page link
  client/homebrew/navbar/account.navitem.jsx
Labels: P2 - minor feature or not urgent

#2426 Add .vscode to .gitignore
  .gitignore
Labels: P3 - low priority

#2428 Send entire brew to HomePage save function
  client/homebrew/pages/homePage/homePage.jsx
Labels: P1 - high priority

#2438 Change ToC to use flexbox
  themes/V3/5ePHB/style.less
Labels: P1 - high priority, 🅖 Chrome Bug

#2452 [UserPage] Add key prop to Brew tags
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
Labels: P2 - minor feature or not urgent

#2450 [UserPage] Fix UserPage groups styling
  client/homebrew/pages/basePages/listPage/listPage.less
Labels: P2 - minor feature or not urgent

#2447 Fix Autosave Default
  client/homebrew/pages/editPage/editPage.jsx
Labels: bug

#2161 Create UI base page
  client/homebrew/homebrew.jsx
  client/homebrew/navbar/account.navitem.jsx
  client/homebrew/pages/accountPage/accountPage.jsx
  client/homebrew/pages/basePages/uiPage/uiPage.jsx
  client/homebrew/pages/basePages/uiPage/uiPage.less
  server/app.js
Labels: P2 - minor feature or not urgent, Reviewed - Awaiting Fixes
