Repository naturalcrit/homebrewery, pull requests merged in 2022-09, with the labels that each got.

#2300 [UserPage] Collapse Brew Groups
  client/homebrew/pages/basePages/listPage/listPage.jsx
  client/homebrew/pages/basePages/listPage/listPage.less
Labels: sub-epic, P2 - minor feature or not urgent

#2316 [UserPage] Add sort type and dir to URL
  client/homebrew/pages/basePages/listPage/listPage.jsx
Labels: sub-epic, P2 - minor feature or not urgent

#2318 [UserPage] Add tags to UserPage BrewItem
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
Labels: sub-epic, P2 - minor feature or not urgent

#2324 Fix conflicts on /new
  client/homebrew/pages/basePages/listPage/listPage.jsx
  client/homebrew/pages/newPage/newPage.jsx
Labels: P1 - high priority, Approved

#2320 [UserPage] Add tags to filter
  client/homebrew/pages/basePages/listPage/listPage.jsx
Labels: sub-epic, P2 - minor feature or not urgent, Reviewed - Awaiting Fixes

#2327 [UserPage] Add sort type & dir to local storage
  client/homebrew/pages/basePages/listPage/listPage.jsx
Labels: sub-epic, P2 - minor feature or not urgent

#2329 [UserPage] Change apostrophe in `usernameWithS`
  client/homebrew/pages/userPage/userPage.jsx
Labels: sub-epic, P2 - minor feature or not urgent

#2332 [UserPage] Show Brew's Meta thumbnail on UserPage
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.less
  server/app.js
Labels: sub-epic, P2 - minor feature or not urgent, Reviewed - Awaiting Fixes

#2388 Add renderer to pageInfo
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/brewRenderer.less
Labels: UI/UX

#2387 Change Monster Stat background color
  themes/V3/5ePHB/style.less
Labels: phb-style

#2396 [Editor] Change folded code text generation
  shared/naturalcrit/codeEditor/codeEditor.jsx
  shared/naturalcrit/codeEditor/codeEditor.less
Labels: Reviewed - Awaiting Fixes
