Repository naturalcrit/homebrewery, pull requests merged in 2022-04, with the labels that each got.

#2080 Add social metadata tags
  client/homebrew/editor/metadataEditor/metadataEditor.jsx
  client/homebrew/editor/metadataEditor/metadataEditor.less
  client/homebrew/thumbnail.png
  client/template.js
  config/default.json
  server/app.js
  server/googleActions.js
  server/homebrew.model.js
Labels: P2 - minor feature or not urgent, Reviewed - Awaiting Fixes

#2052 [LOCAL ONLY] Add passwordless login
  client/homebrew/homebrew.jsx
  client/homebrew/navbar/account.navitem.jsx
  config/default.json
  server/app.js
Labels: Reviewed - Awaiting Fixes

#2061 Add Nodesto font files to 5e, v3
  themes/fonts/5e/Nodesto Caps Condensed Bold Italic.woff2
  themes/fonts/5e/Nodesto Caps Condensed Bold.woff2
  themes/fonts/5e/Nodesto Caps Condensed Italic.woff2
  themes/fonts/5e/Nodesto Caps Condensed.woff2
  themes/fonts/5e/fonts.less
Labels: P2 - minor feature or not urgent
