Repository naturalcrit/homebrewery, pull requests merged in 2023-11, with the labels that each got.

#3035 Add DarkBrewery theme
  scripts/buildHomebrew.js
  themes/codeMirror/customThemes/darkbrewery-v301.css
  themes/codeMirror/editorThemes.json
Labels: P3 - low priority, New Theme, 🔍 Reviewed - Awaiting Fixes

#3073 Add foldAll and unfoldAll buttons to Snippet Bar
  client/homebrew/editor/editor.jsx
  client/homebrew/editor/snippetbar/snippetbar.jsx
  client/homebrew/editor/snippetbar/snippetbar.less
Labels: UI/UX

#3079 fix indent in monster blocks
  themes/V3/5ePHB/style.less
Labels: 🔍 Reviewed - Awaiting Fixes
