Repository naturalcrit/homebrewery, pull requests merged in 2023-04, with the labels that each got.

#2733 Add Metadata Nav Item to SharePage
  client/homebrew/navbar/metadata.navitem.jsx
  client/homebrew/navbar/navbar.less
  client/homebrew/pages/basePages/listPage/listPage.less
  client/homebrew/pages/sharePage/sharePage.jsx
  client/homebrew/pages/sharePage/sharePage.less
  shared/naturalcrit/nav/nav.jsx
  shared/naturalcrit/nav/nav.less
Labels: P2 - minor feature or not urgent, Reviewed - Awaiting Fixes

#2754 Image Inside Blocks
  themes/V3/Blank/style.less
Labels: P2 - minor feature or not urgent

#2805 Dockerfile - Change to npm
  Dockerfile
Labels: P1 - high priority

#2806 Stop image movement in Image Masks
  themes/V3/Blank/style.less
Labels: P2 - minor feature or not urgent

#2654 Part cover - PHB + DMG
  client/icons/book-part-cover.svg
  client/icons/customIcons.less
  themes/V3/5eDMG/style.less
  themes/V3/5ePHB/snippets.js
  themes/V3/5ePHB/snippets/coverpage.gen.js
  themes/V3/5ePHB/snippets/partcoverpage.gen.js
  themes/V3/5ePHB/style.less
  themes/assets/assets.less
  themes/assets/partCoverHeaderDMG.svg
  themes/assets/partCoverHeaderPHB.png
  themes/fonts/5e/Martel Sans Black.woff2
Labels: P2 - minor feature or not urgent
