Repository naturalcrit/homebrewery, pull requests merged in 2023-12, with the labels that each got.

#3133 Add subscript and subscript markdown tokens
  client/homebrew/editor/editor.jsx
  client/homebrew/editor/editor.less
  shared/naturalcrit/codeEditor/codeEditor.jsx
  shared/naturalcrit/markdown.js
Labels: 🔍 Reviewed - Awaiting Fixes

#3116 Fix Firefox printing
  themes/V3/5ePHB/style.less
  themes/V3/Blank/style.less
Labels: P2 - minor feature or not urgent

#3074 Add basic Homebrewery credits snippet
  themes/V3/Blank/snippets.js
  themes/V3/Blank/style.less
Labels: tweak, P2 - minor feature or not urgent, 🔍 R4 - Reviewed - Fixed! ⭐

#3078 Clear invalid CSS from 5ePHB/style.less
  themes/V3/5ePHB/style.less
Labels: 🔍 R4 - Reviewed - Fixed! ⭐

#3131 Add arbitrary tag attribute assignment in mustaches
  client/homebrew/editor/editor.jsx
  shared/naturalcrit/markdown.js
  tests/markdown/mustache-syntax.test.js
Labels: 🔍 R3 - Reviewed - Awaiting Fixes

#3066 Single Quote in in-line styles
  shared/naturalcrit/markdown.js
  tests/markdown/mustache-syntax.test.js
Labels: 🔍 R4 - Reviewed - Fixed! ⭐
