Repository naturalcrit/homebrewery, pull requests merged in 2023-03, with the labels that each got.

#2694 Use secure protocol for Homebrewery mug image
  client/homebrew/pages/homePage/welcome_msg.md
Labels: Approved

#2710 Updated Google Drive icon
  client/homebrew/googleDrive.png
  client/homebrew/googleDrive.svg
  client/homebrew/googleDriveMono.png
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.less
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/editPage/editPage.less
Labels: UI/UX

#2696 [Draft] Trimming Google APIs
  package-lock.json
  package.json
  server/googleActions.js
Labels: Reviewed - Awaiting Fixes

#2681 [EDITOR] Fix div links #2680
  changelog.md
  shared/naturalcrit/markdown.js
  tests/markdown/basic.test.js
Labels: bug, P2 - minor feature or not urgent

#2658 Fix admin pages #2657
  changelog.md
  package.json
  server/admin.api.js
Labels: P2 - minor feature or not urgent

#2625 Windows install script using Chocolatey
  install/README.WINDOWS.md
  install/windows/install.ps1
Labels: P3 - low priority

#2741 Water color image masks part 2 - Center Masks
  client/icons/customIcons.less
  client/icons/mask-center.svg
  themes/V3/Blank/snippets.js
  themes/V3/Blank/snippets/imageMask.gen.js
  themes/V3/Blank/style.less
  themes/assets/waterColorMasks/center/0001.webp
  themes/assets/waterColorMasks/center/0002.webp
  themes/assets/waterColorMasks/center/0003.webp
  themes/assets/waterColorMasks/center/0004.webp
  themes/assets/waterColorMasks/center/0005.webp
  themes/assets/waterColorMasks/center/0006.webp
  themes/assets/waterColorMasks/center/0007.webp
  themes/assets/waterColorMasks/center/0008.webp
  themes/assets/waterColorMasks/center/0009.webp
  themes/assets/waterColorMasks/center/0010.webp
  themes/assets/waterColorMasks/center/0011.webp
  themes/assets/waterColorMasks/center/0012.webp
  themes/assets/waterColorMasks/center/0013.webp
  themes/assets/waterColorMasks/center/0014.webp
  themes/assets/waterColorMasks/center/0015.webp
  themes/assets/waterColorMasks/center/0016.webp
  themes/assets/waterColorMasks/center/special.webp
Labels: P1 - high priority, Reviewed - Awaiting Fixes

#2761 Update engines to Node 16.13.0
  Dockerfile
  package-lock.json
  package.json
Labels: P1 - high priority

#2714 Inside Cover Snippet
  client/icons/book-inside-cover.svg
  client/icons/customIcons.less
  themes/V3/5ePHB/snippets.js
  themes/V3/5ePHB/snippets/coverpage.gen.js
  themes/V3/5ePHB/style.less
  themes/V3/Blank/snippets/imageMask.gen.js
  themes/assets/assets.less
  themes/assets/insideCoverMask.png
Labels: P2 - minor feature or not urgent

#2661 U+00D1 and U+00F1 fix
  themes/fonts/5e/Scaly Sans Caps.woff2
Labels: P2 - minor feature or not urgent
