Repository naturalcrit/homebrewery, pull requests merged in 2023-10, with the labels that each got.

#3067 Add syntax highlighting for definition lists
  client/homebrew/editor/editor.jsx
  client/homebrew/editor/editor.less
Labels: UI/UX, P2 - minor feature or not urgent

#3068 Check for author in author list before increasing views.
  server/app.js
Labels: tweak, P3 - low priority

#3099 Add Share link to Unauthorized Edit Access error message
  client/homebrew/pages/errorPage/errors/errorIndex.js
  server/homebrew.api.js
Labels: P2 - minor feature or not urgent
