Repository naturalcrit/homebrewery, pull requests merged in 2023-09, with the labels that each got.

#3024 Shift manual save to use debounced save function
  client/homebrew/pages/editPage/editPage.jsx
Labels: P2 - minor feature or not urgent

#3013 Change column flow to auto
  themes/V3/5ePHB/style.less
  themes/V3/Blank/style.less
Labels: P2 - minor feature or not urgent

#2889 Remove whitespace from brew titles on UserPage
  client/homebrew/pages/basePages/listPage/listPage.jsx
  server/app.js
  server/homebrew.api.js
Labels: P2 - minor feature or not urgent, 🔍 Reviewed - Awaiting Fixes

#2768 Add editor themes
  client/homebrew/editor/editor.jsx
  client/homebrew/editor/editor.less
  client/homebrew/editor/snippetbar/snippetbar.jsx
  client/homebrew/editor/snippetbar/snippetbar.less
  scripts/buildHomebrew.js
  shared/naturalcrit/codeEditor/codeEditor.jsx
  themes/codeMirror/customEditorStyles.less
  themes/codeMirror/editorThemes.json
Labels: P2 - minor feature or not urgent, 🔍 Reviewed - Awaiting Fixes

#2797 Quote Snippet
  themes/V3/5eDMG/style.less
  themes/V3/5ePHB/snippets.js
  themes/V3/5ePHB/snippets/quote.gen.js
  themes/V3/5ePHB/style.less
Labels: Approved

#2791 Update FAQ and Landpage
  client/homebrew/pages/homePage/welcome_msg.md
  faq.md
Labels: 🔍 Reviewed - Awaiting Fixes
