Repository naturalcrit/homebrewery, pull requests merged in 2024-01, with the labels that each got.

#3215 Color simplification and Darkbrewery snippet color fix
  client/homebrew/editor/snippetbar/snippetbar.less
Labels: cleanup, tweak, 🔍 R0 - Needs first review 👀

#3193 MustacheDivs do not account for prefixed spaces when generating text
  shared/naturalcrit/markdown.js
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3233 Fix Page Deletion issue
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/pages/editPage/editPage.jsx
Labels: P1 - high priority, 🔍 R0 - Needs first review 👀

#3202 Improve Theme selector styling
  client/homebrew/editor/snippetbar/snippetbar.jsx
  client/homebrew/editor/snippetbar/snippetbar.less
Labels: UI/UX, 🔍 R4 - Reviewed - Fixed! ⭐

#3172 Eldeberry Inn Icon font to HB
  themes/V3/5ePHB/style.less
  themes/fonts/icon fonts/Elderberry-Inn-Icons.woff2
  themes/fonts/icon fonts/font-icons.less
Labels: 🔍 R4 - Reviewed - Fixed! ⭐

#3203 fonts as snippets
  client/homebrew/editor/snippetbar/snippetbar.jsx
  client/homebrew/editor/snippetbar/snippetbar.less
  themes/V3/Blank/snippets.js
Labels: 🔍 R3 - Reviewed - Awaiting Fixes

#3118 Identify API errors and send error response
  server/app.js
Labels: P2 - minor feature or not urgent

#3259 New page in new tab
  client/homebrew/navbar/newbrew.navitem.jsx
Labels: tweak

#3264 Fix of admin page
  server/admin.api.js
Labels: cleanup, Approved, 🔍 R0 - Needs first review 👀

#3265 Brew item update
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.less
Labels: tweak, UI/UX, 🔍 R0 - Needs first review 👀

#3267 Clone a brew's tags when cloning a brew.
  server/app.js
Labels: 🔍 R0 - Needs first review 👀
