Repository naturalcrit/homebrewery, pull requests merged in 2024-04, with the labels that each got.

#3389 Align snippet menu icons and names
  client/homebrew/editor/snippetbar/snippetbar.less
  themes/V3/Blank/snippets.js
Labels: tweak, UI/UX, 🔍 R4 - Reviewed - Fixed! ⭐

#3394 1px adjustment to Editor height
  client/homebrew/editor/editor.jsx
Labels: tweak, UI/UX, 🔍 R0 - Needs first review 👀

#3368 Usernames in error pages being displayed as anchors to their userpage
  client/homebrew/pages/errorPage/errors/errorIndex.js
Labels: tweak, UI/UX, 🔍 R4 - Reviewed - Fixed! ⭐

#2981 Cleaning CSS for uniformity
  themes/V3/5ePHB/snippets/coverpage.gen.js
  themes/V3/5ePHB/style.less
Labels: phb-style, 🔍 R4 - Reviewed - Fixed! ⭐

#3398 Refactor accountPage.jsx to functional component
  client/homebrew/homebrew.jsx
  client/homebrew/pages/accountPage/accountPage.jsx
  server/app.js
Labels: cleanup, 🔍 R0 - Needs first review 👀

#3399 Add share link to error pages ONLY IF PUBLISHED
  client/homebrew/pages/errorPage/errors/errorIndex.js
  server/homebrew.api.js
Labels: tweak, UI/UX, 🔍 R4 - Reviewed - Fixed! ⭐

#3388 Custom scrollbar fixes
  client/homebrew/brewRenderer/brewRenderer.less
  client/homebrew/homebrew.less
  shared/naturalcrit/codeEditor/codeEditor.less
Labels: tweak, 🔍 R0 - Needs first review 👀
