Repository naturalcrit/homebrewery, pull requests merged in 2024-12, with the labels that each got.

#3926 Implement Gazook89's suggested fix for missing Page Shadows
  client/homebrew/brewRenderer/brewRenderer.jsx
Labels: bug, tweak, UI/UX, Approved, 🔍 R5 - Approved for merge :100:

#3934 Fix Vault styles
  client/homebrew/pages/vaultPage/vaultPage.less
Labels: bug, tweak, UI/UX, Approved, 🔍 R5 - Approved for merge :100:

#3943 Get Google Brews with user auth if owner
  server/googleActions.js
  server/homebrew.api.js
  server/homebrew.api.spec.js
Labels: 🔍 R0 - Needs first review 👀

#3942 Create backend batch re-author framework
  package-lock.json
  package.json
  server/app.js
  server/homebrew.api.js
  server/middleware/check-client-version.js
Labels: feature, Epic, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3863 Fix crashes if title is invalid as URI
  client/homebrew/pages/editPage/editPage.jsx
Labels: bug, tweak, P3 - low priority, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3905 Fixes #3904 - content negotiation test failure
  .circleci/config.yml
  package.json
  server/middleware/content-negotiation.js
  server/middleware/content-negotiation.spec.js
Labels: P2 - minor feature or not urgent, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3953 Fix admin added as author #3952
  server/admin.api.js
Labels: bug, P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3909 V4 proposed non-breaking space token
  .circleci/config.yml
  package.json
  shared/naturalcrit/markdown.js
  tests/markdown/non-breaking-spaces.test.js
Labels: 🔍 R3 - Reviewed - Awaiting Fixes 🔧, 🚀 V4, experiment

#3960 Add google refresh info to error page #3955
  client/homebrew/pages/errorPage/errors/errorIndex.js
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3845 Intersection Observers for getting "Current Page(s)"
  client/components/Anchored.jsx
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/brewRenderer.less
  client/homebrew/brewRenderer/toolBar/toolBar.jsx
  client/homebrew/brewRenderer/toolBar/toolBar.less
Labels: UI/UX, P2 - minor feature or not urgent, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3965 Implement content-visibility on pages
  themes/Legacy/5ePHB/style.less
  themes/V3/Blank/style.less
Labels: UI/UX, Approved, 🔍 R0 - Needs first review 👀

#3852 Refactor brewItem into functional component
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
Labels: cleanup, tweak, Approved, 🔍 R0 - Needs first review 👀

#3922 Refactor sharepage as functional comp
  client/homebrew/pages/sharePage/sharePage.jsx
Labels: cleanup, Approved, 🔍 R0 - Needs first review 👀
