Repository naturalcrit/homebrewery, pull requests merged in 2024-05, with the labels that each got.

#3447 Add edit link to share page if user is author
  client/homebrew/pages/sharePage/sharePage.jsx
  server/app.js
Labels: feature, tweak, Approved

#3457 icon for edit link in sharepage
  client/homebrew/pages/sharePage/sharePage.jsx
Labels: tweak, Approved

#3434 Add DOM Purify to BrewRenderer
  client/homebrew/brewRenderer/brewRenderer.jsx
  package-lock.json
  package.json
Labels: P0 - security or data loss, 🔍 R0 - Needs first review 👀

#3432 Fix icon fonts
  themes/fonts/iconFonts/elderberryInn.js
  themes/fonts/iconFonts/elderberryInn.less
Labels: 🔍 R4 - Reviewed - Fixed! ⭐

#3404 Add proficiency bonus to monster statblocks
  themes/V3/5ePHB/snippets/monsterblock.gen.js
  themes/V3/5ePHB/style.less
Labels: tweak, 🔍 R4 - Reviewed - Fixed! ⭐

#3420 RPG Awesome Redux
  shared/naturalcrit/codeEditor/autocompleteEmoji.js
  shared/naturalcrit/codeEditor/codeEditor.less
  shared/naturalcrit/markdown.js
  themes/V3/Blank/style.less
  themes/fonts/iconFonts/elderberryInn.js
  themes/fonts/iconFonts/game-icons_license.md
  themes/fonts/iconFonts/gameIcons.js
  themes/fonts/iconFonts/gameIcons.less
  themes/fonts/iconFonts/gameIcons.woff
Labels: 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3482 Clean up unused declarations
  client/admin/brewCleanup/brewCleanup.jsx
  client/admin/brewCompress/brewCompress.jsx
  client/components/combobox.jsx
  client/homebrew/brewRenderer/errorBar/errorBar.jsx
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.jsx
  client/homebrew/editor/metadataEditor/metadataEditor.jsx
  client/homebrew/navbar/help.navitem.jsx
  client/homebrew/navbar/metadata.navitem.jsx
  client/homebrew/navbar/print.navitem.jsx
  client/homebrew/navbar/reddit.navitem.jsx
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
  client/homebrew/pages/newPage/newPage.jsx
  client/homebrew/pages/printPage/printPage.jsx
  client/homebrew/pages/userPage/userPage.jsx
  server/googleActions.js
  shared/homebrewery/renderWarnings/renderWarnings.jsx
  shared/naturalcrit/codeEditor/codeEditor.jsx
  shared/naturalcrit/splitPane/splitPane.jsx
Labels: cleanup, P3 - low priority, 🔍 R0 - Needs first review 👀

#3477 Fix `ref` issues
  client/homebrew/editor/editor.jsx
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/homePage/homePage.jsx
  client/homebrew/pages/newPage/newPage.jsx
  client/homebrew/pages/printPage/printPage.jsx
  shared/naturalcrit/codeEditor/codeEditor.jsx
  shared/naturalcrit/splitPane/splitPane.jsx
Labels: tweak, 🔍 R4 - Reviewed - Fixed! ⭐

#3491 Print directly from Edit/Share/New pages
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/brewRenderer.less
  client/homebrew/homebrew.jsx
  client/homebrew/navbar/print.navitem.jsx
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/hijackPrint.js
  client/homebrew/pages/newPage/newPage.jsx
  client/homebrew/pages/printPage/printPage.jsx
  client/homebrew/pages/printPage/printPage.less
  client/homebrew/pages/sharePage/sharePage.jsx
  server/app.js
  shared/helpers.js
Labels: bug, P1 - high priority, 🔍 R0 - Needs first review 👀
