Repository naturalcrit/homebrewery, pull requests merged in 2024-03, with the labels that each got.

#3292 Combine nav and navbar styles
  client/homebrew/navbar/navbar.less
  shared/naturalcrit/nav/nav.jsx
  shared/naturalcrit/nav/nav.less
Labels: cleanup, Approved, 🔍 R4 - Reviewed - Fixed! ⭐

#3288 FA to 6.5.1
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/template.js
Labels: tweak, Approved, 🔍 R0 - Needs first review 👀

#3286 Phb vs Blank theme management
  themes/V3/5ePHB/style.less
  themes/V3/Blank/style.less
  themes/V3/Journal/style.less
Labels: cleanup, tweak, ❌ Missing from V3, 🔍 R0 - Needs first review 👀

#3289 New Brew from Local file
  client/homebrew/navbar/newbrew.navitem.jsx
  server/app.js
  shared/helpers.js
Labels: 🔍 R4 - Reviewed - Fixed! ⭐

#3345 Updated Table of Contents snippet
  themes/V3/5ePHB/snippets/tableOfContents.gen.js
Labels: phb-style, tweak, 🔍 R4 - Reviewed - Fixed! ⭐

#3278 Add type attribute to all stylesheet import link tags
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/pages/basePages/listPage/listPage.jsx
  client/homebrew/pages/printPage/printPage.jsx
  client/template.js
  shared/naturalcrit/codeEditor/codeEditor.jsx
Labels: tweak

#3291 Small navigation fixes
  client/homebrew/navbar/navbar.less
  shared/naturalcrit/nav/nav.jsx
Labels: tweak, UI/UX, 🔍 R3 - Reviewed - Awaiting Fixes

#3129 Add Multi-line Dictionary Definition (<dd>) rows.
  client/homebrew/editor/editor.jsx
  client/homebrew/editor/editor.less
  package.json
  shared/naturalcrit/markdown.js
  tests/markdown/marked-extensions.test.js
Labels: 🔍 R4 - Reviewed - Fixed! ⭐

#3348 Font fix, df to icon fonts, remove duplication
  themes/V3/5ePHB/style.less
  themes/V3/Blank/style.less
  themes/fonts/5e/fonts.less
  themes/fonts/icon fonts/dicefont.less
  themes/fonts/icon fonts/dicefont.woff
  themes/fonts/icon fonts/dicefont.woff2
  themes/fonts/icon fonts/dicefont_license.md
Labels: cleanup, tweak, Approved, 🔍 R0 - Needs first review 👀

#3327 Add administrative brew locking function
  client/homebrew/pages/errorPage/errors/errorIndex.js
  server/homebrew.api.js
  server/homebrew.api.spec.js
Labels: P3 - low priority, 🔍 R4 - Reviewed - Fixed! ⭐

#3375 Fix crash when match is undefined
  shared/naturalcrit/markdown.js
Labels: P1 - high priority, 🔍 R0 - Needs first review 👀

#3379 Change Marked extension priority order
  shared/naturalcrit/markdown.js
Labels: bug, P1 - high priority

#3346 Custom scrollbar
  client/homebrew/brewRenderer/brewRenderer.less
  client/homebrew/homebrew.less
  shared/naturalcrit/codeEditor/codeEditor.less
Labels: tweak, UI/UX, 🔍 R3 - Reviewed - Awaiting Fixes 🔧
