Repository naturalcrit/homebrewery, pull requests merged in 2024-07, with the labels that each got.

#3555 Fix ToC generator snippet
  themes/V3/5ePHB/snippets/tableOfContents.gen.js
Labels: P1 - high priority, 🔍 R0 - Needs first review 👀

#3560 Limit htmlString to the first element ONLY
  shared/naturalcrit/markdown.js
  tests/markdown/mustache-syntax.test.js
Labels: bug, P1 - high priority, 🔍 R0 - Needs first review 👀

#3569 Unset text-decoration on Brew Item links
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.less
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3567 Add additional styles to SolberaImitationRemake font declaration
  themes/fonts/5e/fonts.less
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3321 Enable User Brew theme selection
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/editor/editor.jsx
  client/homebrew/editor/metadataEditor/metadataEditor.jsx
  client/homebrew/editor/metadataEditor/metadataEditor.less
  client/homebrew/editor/snippetbar/snippetbar.jsx
  client/homebrew/homebrew.jsx
  client/homebrew/navbar/error-navitem.jsx
  client/homebrew/navbar/error-navitem.less
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/errorPage/errors/errorIndex.js
  client/homebrew/pages/homePage/homePage.jsx
  client/homebrew/pages/newPage/newPage.jsx
  client/homebrew/pages/sharePage/sharePage.jsx
  config/default.json
  package.json
  server/app.js
  server/homebrew.api.js
  server/homebrew.api.spec.js
  server/homebrew.model.js
  shared/helpers.js
  themes/V3/5ePHB/settings.json
  themes/V3/Journal/settings.json
  themes/themes.json
Labels: sub-epic, UI/UX, 🔍 R2 - Reviewed - Needs Help 🫱, Approved
