Repository naturalcrit/homebrewery, pull requests merged in 2024-09, with the labels that each got.

#3263 [FEATURE]: Vault page (search published brews) (alt title Archive)
  client/homebrew/homebrew.jsx
  client/homebrew/navbar/vault.navitem.jsx
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
  client/homebrew/pages/errorPage/errors/errorIndex.js
  client/homebrew/pages/homePage/homePage.jsx
  client/homebrew/pages/userPage/userPage.jsx
  client/homebrew/pages/vaultPage/vaultPage.jsx
  client/homebrew/pages/vaultPage/vaultPage.less
  server/app.js
  server/homebrew.api.js
  server/homebrew.api.spec.js
  server/vault.api.js
  shared/naturalcrit/splitPane/splitPane.jsx
Labels: Epic, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐

#3704 Update gitattributes to stop JSON from constantly appearing as modified
  .gitattributes
Labels: P3 - low priority, 🔍 R0 - Needs first review 👀

#3696 All Snippet entries that have subsnippets but not generators.
  client/homebrew/editor/snippetbar/snippetbar.jsx
Labels: cleanup, tweak, 🔍 R0 - Needs first review 👀

#3639 Rework page counters for skipping and resets.
  themes/V3/5ePHB/snippets/tableOfContents.gen.js
  themes/V3/Blank/style.less
Labels: 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐

#3705 Add button to toggle Preview tools
  client/homebrew/brewRenderer/toolBar/toolBar.jsx
  client/homebrew/brewRenderer/toolBar/toolBar.less
Labels: UI/UX, P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3679 Add Page number alteration snippets
  themes/V3/Blank/snippets.js
Labels: blocked, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐, New Snippet

#3714 Meta Tags for the Vault Page
  server/app.js
Labels: tweak, UI/UX, Approved, 🔍 R5 - Approved for merge :100:

#3719 Logic rewrite of tableOfContents.gen
  themes/V3/5ePHB/snippets/tableOfContents.gen.js
Labels: cleanup

#3481 Add API endpoint to get metadata from brews
  server/app.js
Labels: Epic, tweak, 🔍 R5 - Approved for merge :100:

#3484 Live Mirror Editor position in Preview pane.
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/editor/editor.jsx
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/homePage/homePage.jsx
  client/homebrew/pages/newPage/newPage.jsx
  shared/naturalcrit/splitPane/splitPane.jsx
  shared/naturalcrit/splitPane/splitPane.less
Labels: feature, UI/UX, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐

#3689 Add Style Tab Snippets for Globally toggling additional header inclusion
  themes/V3/5ePHB/snippets.js
  themes/V3/5ePHB/style.less
Labels: 🔍 R3 - Reviewed - Awaiting Fixes 🔧, Approved, New Snippet

#3711 Store limited Brew History in Local Storage
  client/homebrew/editor/editor.jsx
  client/homebrew/editor/snippetbar/snippetbar.jsx
  client/homebrew/editor/snippetbar/snippetbar.less
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/utils/versionHistory.js
  server/app.js
Labels: P3 - low priority, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐, experiment

#3692 Style snippets, more page sizes, A3, A5, Card
  themes/V3/Blank/snippets.js
Labels: 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐, New Snippet

#3634 Fix Nav flow
  client/homebrew/navbar/navbar.less
  package.json
Labels: tweak, UI/UX, Approved, 🔍 R0 - Needs first review 👀

#3724 Add Pagella Font family to Blank
  themes/V3/Blank/snippets.js
  themes/V3/Blank/style.less
  themes/fonts/Blank/fonts.less
  themes/fonts/Blank/texgyrepagella-bold.woff2
  themes/fonts/Blank/texgyrepagella-bolditalic.woff2
  themes/fonts/Blank/texgyrepagella-italic.woff2
  themes/fonts/Blank/texgyrepagella-regular.woff2
Labels: 🔍 R0 - Needs first review 👀

#3736 Properties Editor Structure and Style
  client/homebrew/editor/metadataEditor/metadataEditor.jsx
  client/homebrew/editor/metadataEditor/metadataEditor.less
  client/homebrew/editor/stringArrayEditor/stringArrayEditor.jsx
Labels: 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3723 Add sorting options to Vault Page
  client/homebrew/pages/vaultPage/vaultPage.jsx
  client/homebrew/pages/vaultPage/vaultPage.less
  server/vault.api.js
Labels: feature, sub-epic, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3765 Change default value of currentEditorCursorPageNum
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/pages/sharePage/sharePage.jsx
Labels: P1 - high priority, 🔍 R0 - Needs first review 👀

#3767 Add zoom property to BrewRenderer print styling
  client/homebrew/brewRenderer/brewRenderer.less
Labels: P1 - high priority

#3778 fix lang on share page
  client/homebrew/pages/sharePage/sharePage.jsx
Labels: bug, tweak, Approved
