Repository naturalcrit/homebrewery, pull requests merged in 2024-08, with the labels that each got.

#3608 Fix tests post v3.14.0
  server/homebrew.api.spec.js
Labels: P1 - high priority, 🔍 R0 - Needs first review 👀

#3580 Fix Table of Contents uppercasing
  themes/V3/5ePHB/snippets/tableOfContents.gen.js
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3564 Stop Ink Friendly snippet making text unselectable in output PDF
  themes/V3/5ePHB/snippets.js
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3517 Solve for .descriptive and .wide not getting along
  themes/V3/5ePHB/style.less
Labels: 🔍 R4 - Reviewed - Fixed! ⭐

#3526 Fixing Monster Frame background in Safari for iphone and ipad
  themes/V3/5ePHB/style.less
  themes/assets/assets.less
Labels: tweak, ❌ Missing from V3, P2 - minor feature or not urgent, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3615 Prevent self-selection of User Theme
  client/homebrew/editor/metadataEditor/metadataEditor.jsx
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3587 Add new var math functions
  shared/naturalcrit/markdown.js
Labels: P2 - minor feature or not urgent, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3516 Update table of content list-item breakage rules for wide table of contents
  themes/V3/5ePHB/style.less
Labels: tweak, 🔍 R1 - Reviewed - Needs Discussion 💬, Approved

#3585 Add Code folding on CSS style tab
  client/homebrew/editor/editor.jsx
  shared/naturalcrit/codeEditor/codeEditor.jsx
  shared/naturalcrit/codeEditor/fold-css.js
  shared/naturalcrit/codeEditor/fold-pages.js
Labels: 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3588 Add disableMeta prop to SharePage
  client/homebrew/homebrew.jsx
  client/homebrew/pages/sharePage/sharePage.jsx
Labels: P2 - minor feature or not urgent, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3624 Fix var name substring clash #3613
  shared/naturalcrit/markdown.js
  tests/markdown/variables.test.js
Labels: bug, P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3625 Tweak variable math split regex
  shared/naturalcrit/markdown.js
  tests/markdown/variables.test.js
Labels: bug, P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3483 Add Jump-To hotkeys
  client/homebrew/editor/editor.jsx
Labels: 🔍 R0 - Needs first review 👀

#3643 Change order of operations in mask img transform
  themes/V3/Blank/style.less
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3515 Create globally unique Header IDs when marked parses.
  package-lock.json
  shared/naturalcrit/markdown.js
Labels: ❌ Missing from V3, 🔍 R0 - Needs first review 👀

#3499 Viewer tools
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/brewRenderer.less
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.less
  client/homebrew/brewRenderer/toolBar/toolBar.jsx
  client/homebrew/brewRenderer/toolBar/toolBar.less
  client/homebrew/editor/editor.jsx
  client/homebrew/navbar/navbar.less
Labels: sub-epic, UI/UX, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3644 Prevent styling of lines inside folded sections
  client/homebrew/editor/editor.jsx
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#3075 Add route to get brew styling
  package.json
  server/app.js
  server/homebrew.api.js
  server/homebrew.api.spec.js
Labels: 🔍 R4 - Reviewed - Fixed! ⭐, experiment

#3677 Account page handling of invalid user
  client/homebrew/pages/errorPage/errors/errorIndex.js
  server/app.js
Labels: P0 - security or data loss, Approved, 🔍 R0 - Needs first review 👀

#3687 Fix Image Wrap icons
  client/icons/customIcons.less
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀
