Repository naturalcrit/homebrewery, pull requests merged in 2024-10, with the labels that each got.

#3793 Fix brew link generation based on brew stub existence
  client/homebrew/navbar/recent.navitem.jsx
Labels: bug, tweak, UI/UX, 🔍 R0 - Needs first review 👀

#3802 Remove Unused Nav Components
  client/homebrew/navbar/editTitle.navitem.jsx
  client/homebrew/navbar/reddit.navitem.jsx
Labels: 🔍 R5 - Approved for merge :100:

#3132 Add local statics for images and typefaces
  config/default.json
  server/app.js
  server/middleware/content-negotiation.js
Labels: 🔍 R0 - Needs first review 👀

#2586 Experimental notification DB
  client/admin/admin.jsx
  client/admin/admin.less
  client/admin/brewCleanup/brewCleanup.less
  client/admin/brewCompress/brewCompress.less
  client/admin/brewLookup/brewLookup.less
  client/admin/brewUtils/brewCleanup/brewCleanup.jsx
  client/admin/brewUtils/brewCleanup/brewCleanup.less
  client/admin/brewUtils/brewCompress/brewCompress.jsx
  client/admin/brewUtils/brewCompress/brewCompress.less
  client/admin/brewUtils/brewLookup/brewLookup.jsx
  client/admin/brewUtils/brewUtils.jsx
  client/admin/brewUtils/stats/stats.jsx
  client/admin/brewUtils/stats/stats.less
  client/admin/notificationUtils/notificationAdd/notificationAdd.jsx
  client/admin/notificationUtils/notificationAdd/notificationAdd.less
  client/admin/notificationUtils/notificationLookup/notificationLookup.jsx
  client/admin/notificationUtils/notificationLookup/notificationLookup.less
  client/admin/notificationUtils/notificationUtils.jsx
  client/admin/stats/stats.less
  package.json
  server/admin.api.js
  server/admin.api.spec.js
  server/notifications.model.js
Labels: experiment, 🔍 R5 - Approved for merge :100:

#3492 Fix admin vulnerability to Brute Force
  client/homebrew/pages/errorPage/errors/errorIndex.js
  server/admin.api.js
Labels: P0 - security or data loss, 🔍 R5 - Approved for merge :100:

#3688 Change BrewRenderer background in Heroku test deployments
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/brewRenderer.less
  server/app.js
Labels: P3 - low priority, 🔍 R3 - Reviewed - Awaiting Fixes 🔧, experiment

#3808 Merge V3.15.2
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.jsx
  server/app.js
  server/googleActions.js
Labels: P1 - high priority, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3815 Tweak color of Brew Renderer background text
  client/homebrew/brewRenderer/brewRenderer.jsx
Labels: P3 - low priority, 🔍 R0 - Needs first review 👀

#3838 Allow Markdown/Style to update on any text change
  client/homebrew/brewRenderer/brewRenderer.jsx
Labels: P1 - high priority

#3635 Snippet bar wrapping
  client/homebrew/editor/editor.less
  client/homebrew/editor/snippetbar/snippetbar.jsx
  client/homebrew/editor/snippetbar/snippetbar.less
Labels: tweak, UI/UX, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐

#3844 Catch IndexedDB errors
  client/homebrew/pages/editPage/editPage.jsx
Labels: bug, P1 - high priority, 🔍 R0 - Needs first review 👀

#3506 Get external link and scroll to element
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/brewRenderer.less
Labels: feature, UI/UX, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐

#3805 Add notification client side
  client/admin/notificationUtils/notificationAdd/notificationAdd.jsx
  client/admin/notificationUtils/notificationLookup/notificationLookup.jsx
  client/components/dialog.jsx
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.jsx
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.less
  server/admin.api.js
Labels: feature, UI/UX, Approved, 🔍 R5 - Approved for merge :100:

#3853 fix snippetbar weirdness
  client/homebrew/editor/snippetbar/snippetbar.jsx
  client/homebrew/editor/snippetbar/snippetbar.less
Labels: bug, cleanup, tweak, UI/UX, 🔍 R5 - Approved for merge :100:

#3851 Refactor UserPage as a functional component
  client/homebrew/pages/userPage/userPage.jsx
Labels: cleanup, tweak, Approved, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐

#3823 Clean up DOM
  client/homebrew/navbar/navbar.less
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/homePage/homePage.jsx
  client/homebrew/pages/homePage/welcome_msg.md
  client/homebrew/pages/newPage/newPage.jsx
  client/homebrew/pages/sharePage/sharePage.less
  client/homebrew/pages/vaultPage/vaultPage.jsx
  shared/naturalcrit/nav/nav.jsx
Labels: cleanup, tweak, 🔍 R0 - Needs first review 👀

#3855 Refactor splitpane as a functional component
  shared/naturalcrit/splitPane/splitPane.jsx
  shared/naturalcrit/splitPane/splitPane.less
Labels: cleanup, Approved, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐

#3861 Vault styles quickfix
  client/homebrew/pages/vaultPage/vaultPage.less
Labels: tweak

#3548 Improve HTML sanitization
  .circleci/config.yml
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/safeHTML.js
  package-lock.json
  package.json
  tests/html/safeHTML.test.js
Labels: P1 - high priority, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐

#3816 Refactor version history to use custom store wrapper
  client/homebrew/utils/customIDBStore.js
  client/homebrew/utils/versionHistory.js
Labels: cleanup, P3 - low priority, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐
