Repository naturalcrit/homebrewery, pull requests merged in 2024-06, with the labels that each got.

#3382 Add blocking notification to EditPage
  client/components/dialog.jsx
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.jsx
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.less
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/editPage/lockNotification/lockNotification.jsx
  client/homebrew/pages/editPage/lockNotification/lockNotification.less
  client/homebrew/pages/errorPage/errors/errorIndex.js
  server/homebrew.api.js
  server/homebrew.api.spec.js
  shared/homebrewery/renderWarnings/renderWarnings.jsx
  shared/homebrewery/renderWarnings/renderWarnings.less
Labels: sub-epic, P2 - minor feature or not urgent, 🔍 R4 - Reviewed - Fixed! ⭐

#3522 Tweak CM page line brightness on dark themes
  themes/codeMirror/customEditorStyles.less
Labels: tweak, P3 - low priority, 🔍 R0 - Needs first review 👀

#3261 Table of Contents Snippet exclusion system
  themes/V3/5ePHB/snippets.js
  themes/V3/5ePHB/snippets/tableOfContents.gen.js
  themes/V3/5ePHB/style.less
Labels: 🔍 R3 - Reviewed - Awaiting Fixes 🔧, 🔍 R4 - Reviewed - Fixed! ⭐
