Repository naturalcrit/homebrewery, pull requests merged in 2024-02, with the labels that each got.

#3199 Yet another Brew Variables PR
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/homePage/homePage.jsx
  client/homebrew/pages/newPage/newPage.jsx
  package-lock.json
  package.json
  shared/naturalcrit/markdown.js
  tests/markdown/variables.test.js
Labels: complicated, P2 - minor feature or not urgent, 🔍 R3 - Reviewed - Awaiting Fixes

#3299 popup update 3.11
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.jsx
Labels: tweak, UI/UX

#3273 brew fix commas
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
Labels: tweak, 🔍 R4 - Reviewed - Fixed! ⭐

#3296 Fix lang on print
  client/homebrew/pages/printPage/printPage.jsx
Labels: tweak, ❌ Missing from V3, P1 - high priority, Approved, 🔍 R0 - Needs first review 👀

#3316 Fix sanitizeScriptTags when content is null
  client/homebrew/brewRenderer/brewRenderer.jsx
Labels: P1 - high priority

#3297 Changed background-attachment: fixed on the monster frame
  themes/V3/5ePHB/style.less
Labels: tweak, ❌ Missing from V3, Approved

#3197 Add DiceFont support to Homebrewery
  themes/fonts/5e/dicefont.less
  themes/fonts/5e/dicefont.woff
  themes/fonts/5e/dicefont.woff2
  themes/fonts/5e/dicefont_license.md
  themes/fonts/5e/fonts.less
Labels: P2 - minor feature or not urgent, 🔍 R4 - Reviewed - Fixed! ⭐

#3325 Added new editor theme named darkvision
  themes/codeMirror/customThemes/darkvision.css
  themes/codeMirror/editorThemes.json
Labels: New Theme

#3165 Add tag filtering
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.less
  client/homebrew/pages/basePages/listPage/listPage.jsx
  client/homebrew/pages/basePages/listPage/listPage.less
Labels: P2 - minor feature or not urgent, 🔍 R4 - Reviewed - Fixed! ⭐

#3330 Remove background-attachment property from .monster.frame
  themes/V3/5ePHB/style.less
Labels: tweak, ❌ Missing from V3, Approved

#3323 Fix syntax highlighting on sub and superscript
  client/homebrew/editor/editor.jsx
Labels: 🔍 R4 - Reviewed - Fixed! ⭐
