Repository naturalcrit/homebrewery, pull requests merged in 2024-11, with the labels that each got.

#3799 View Modes - Single / Facing Pages / "Flow" arrangements
  client/components/Anchored.jsx
  client/components/Anchored.less
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/brewRenderer.less
  client/homebrew/brewRenderer/toolBar/toolBar.jsx
  client/homebrew/brewRenderer/toolBar/toolBar.less
  client/icons/customIcons.less
  client/icons/facing-spread.svg
  client/icons/flow-spread.svg
  client/icons/single-spread.svg
  package.json
Labels: UI/UX, P3 - low priority, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐

#3885 Fix Dialog.jsx to prevent crashes
  client/components/dialog.jsx
Labels: bug, tweak, P1 - high priority

#3820 Add script fix tool to Admin page #3801
  client/admin/brewUtils/brewLookup/brewLookup.jsx
  client/admin/brewUtils/brewLookup/brewLookup.less
  server/admin.api.js
  server/homebrew.api.js
Labels: P2 - minor feature or not urgent, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3890 Update Core.less and reset.less
  client/homebrew/brewRenderer/toolBar/toolBar.less
  client/homebrew/editor/metadataEditor/metadataEditor.less
  shared/naturalcrit/styles/core.less
  shared/naturalcrit/styles/reset.less
Labels: 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐

#3735 TagInput - Functional component for tag-like inputs
  client/homebrew/editor/metadataEditor/metadataEditor.jsx
  client/homebrew/editor/metadataEditor/metadataEditor.less
  client/homebrew/editor/stringArrayEditor/stringArrayEditor.jsx
  client/homebrew/editor/tagInput/tagInput.jsx
  client/homebrew/editor/tagInput/tagInput.less
Labels: UI/UX, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐
