Repository naturalcrit/homebrewery, pull requests merged in 2025-03, with the labels that each got.

#4005 Workaround for unclosed <pre> blocks before rendering.
  client/homebrew/brewRenderer/brewRenderer.jsx
Labels: bug, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#4083 Remove unused DOMPurify package
  package-lock.json
  package.json
Labels: dependencies, P3 - low priority, 🔍 R0 - Needs first review 👀

#4080 Vault fixes
  changelog.md
  client/homebrew/pages/vaultPage/vaultPage.jsx
  client/homebrew/pages/vaultPage/vaultPage.less
  server/vault.api.js
Labels: tweak, 🔍 R0 - Needs first review 👀

#4095 [LOCAL]: Fix cors issue in local network
  server/app.js
Labels: tweak, Approved, 🔍 R0 - Needs first review 👀, javascript

#4099 Fix minor v3.18.0 issues
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.less
  client/homebrew/pages/basePages/uiPage/uiPage.less
  shared/naturalcrit/markdown.js
  tests/markdown/definition-lists.test.js
  tests/markdown/hard-breaks.test.js
  themes/V3/5ePHB/style.less
  themes/V3/Blank/style.less
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#4113 Fix CORS regex test for local installs
  server/app.js
Labels: P1 - high priority, 🔍 R0 - Needs first review 👀

#4014 Fix space issue in image tags
  shared/naturalcrit/markdown.js
  tests/markdown/variables.test.js
Labels: bug, 🔍 R4 - Fixed! Awaiting re-review⭐

#3664 Relocate general purpose snippets still in 5ePHB theme to Blank
  themes/Legacy/5ePHB/style.less
  themes/V3/5eDMG/style.less
  themes/V3/5ePHB/snippets.js
  themes/V3/5ePHB/style.less
  themes/V3/Blank/snippets.js
  themes/V3/Blank/snippets/index.gen.js
  themes/V3/Blank/snippets/tableOfContents.gen.js
  themes/V3/Blank/style.less
  themes/V3/Journal/style.less
Labels: UI/UX, 🔍 R3 - Reviewed - Awaiting Fixes 🔧, Approved

#4107 "Workaround" for bad \page mustache blocks
  client/homebrew/brewRenderer/brewRenderer.jsx
Labels: 🔍 R5 - Approved for merge :100:
