Repository naturalcrit/homebrewery, pull requests merged in 2025-05, with the labels that each got.

#4158 Change page overflow from hidden to clip
  themes/V3/Blank/style.less
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀

#4178 Add author as metadata for link unfurling
  server/app.js
Labels: tweak, Approved, 🔍 R0 - Needs first review 👀

#4169 Localise out Fontawesome use.
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/template.js
  font-awesome-source/README.md
  font-awesome-source/deploy.bash
  themes/fonts/iconFonts/fa-brands-400.woff2
  themes/fonts/iconFonts/fa-regular-400.woff2
  themes/fonts/iconFonts/fa-solid-900.woff2
  themes/fonts/iconFonts/fa-v4compatibility.woff2
  themes/fonts/iconFonts/fontAwesome.less
  themes/fonts/iconFonts/fontawesome-brands.less
  themes/fonts/iconFonts/fontawesome-free.less
  themes/fonts/iconFonts/fontawesome-regular.less
  themes/fonts/iconFonts/fontawesome-solid.less
Labels: UI/UX, 🔍 R4 - Fixed! Awaiting re-review⭐

#4156 toolbar, small fixes
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/toolBar/toolBar.jsx
  client/homebrew/brewRenderer/toolBar/toolBar.less
  client/homebrew/editor/editor.less
Labels: UI/UX, 🔍 R5 - Approved for merge :100:

#4191 Fix-darkbrewery
  client/homebrew/editor/snippetbar/snippetbar.less
  themes/codeMirror/customThemes/darkbrewery-v301.css
  themes/codeMirror/customThemes/darkbrewery.css
  themes/codeMirror/editorThemes.json
Labels: cleanup, UI/UX, Approved, 🔍 R5 - Approved for merge :100:

#4170 Tweak icon height
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.jsx
  client/homebrew/pages/basePages/listPage/brewItem/brewItem.less
  client/homebrew/thumbnail.svg
  themes/assets/naturalCritLogoBlack.svg
Labels: UI/UX, 🔍 R4 - Fixed! Awaiting re-review⭐

#4207 Fix Codemirror Overflow
  changelog.md
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/editor/editor.jsx
  client/homebrew/editor/editor.less
Labels: UI/UX, 🔍 R0 - Needs first review 👀, javascript
