Repository naturalcrit/homebrewery, pull requests merged in 2025-04, with the labels that each got.

#4088 Add pageNumber brew variable
  package-lock.json
  package.json
  shared/naturalcrit/markdown.js
  tests/markdown/variables.test.js
  themes/V3/Blank/snippets.js
Labels: P2 - minor feature or not urgent, 🔍 R4 - Fixed! Awaiting re-review⭐, experiment

#4104 CodeEditor overflow issue fix
  client/homebrew/editor/editor.jsx
  client/homebrew/editor/editor.less
Labels: tweak, 🔍 R5 - Approved for merge :100:

#3421 Add lock routes
  client/admin/admin.jsx
  client/admin/lockTools/lockTools.jsx
  client/admin/lockTools/lockTools.less
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/editPage/lockNotification/lockNotification.jsx
  client/homebrew/pages/editPage/lockNotification/lockNotification.less
  client/homebrew/pages/errorPage/errors/errorIndex.js
  server/admin.api.js
  server/admin.api.spec.js
  server/app.js
  server/homebrew.api.js
  server/homebrew.api.spec.js
  server/homebrew.model.js
Labels: sub-epic, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#4046 Migrate nonbreaking spaces to npm module.
  package-lock.json
  package.json
  shared/naturalcrit/markdown.js
  tests/markdown/non-breaking-spaces.test.js
Labels: 🔍 R4 - Fixed! Awaiting re-review⭐

#4044 Migrate the justified paragraphs extension to an NPM
  package-lock.json
  package.json
  shared/naturalcrit/markdown.js
Labels: 🔍 R4 - Fixed! Awaiting re-review⭐

#4049 Move Definition Lists extensions to NPM
  .circleci/config.yml
  package-lock.json
  package.json
  shared/naturalcrit/markdown.js
Labels: dependencies, 🔍 R4 - Fixed! Awaiting re-review⭐

#4147 Add print-specific styling for facing and flow page layouts
  client/homebrew/brewRenderer/brewRenderer.less
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀
