Repository naturalcrit/homebrewery, pull requests merged in 2025-02, with the labels that each got.

#4026 fix undefined value in errorIndex.js if brew doesn't exist
  client/homebrew/pages/errorPage/errors/errorIndex.js
Labels: bug, tweak, P1 - high priority, 🔍 R0 - Needs first review 👀

#4036 Correct typo in date of v3.17.0
  changelog.md
Labels: P2 - minor feature or not urgent, 🔍 R0 - Needs first review 👀, documentation

#4031 Add Admin function to get list of brews by username
  client/admin/admin.jsx
  client/admin/authorUtils/authorLookup/authorLookup.jsx
  client/admin/authorUtils/authorLookup/authorLookup.less
  client/admin/authorUtils/authorUtils.jsx
  server/admin.api.js
Labels: P2 - minor feature or not urgent, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#4022 Update admin
  client/admin/admin.jsx
  client/admin/admin.less
  client/admin/authorUtils/authorLookup/authorLookup.jsx
  client/admin/authorUtils/authorLookup/authorLookup.less
  client/admin/brewUtils/brewCleanup/brewCleanup.jsx
  client/admin/brewUtils/brewCleanup/brewCleanup.less
  client/admin/brewUtils/brewCompress/brewCompress.jsx
  client/admin/brewUtils/brewCompress/brewCompress.less
  client/admin/brewUtils/brewLookup/brewLookup.jsx
  client/admin/brewUtils/brewLookup/brewLookup.less
  client/admin/brewUtils/brewUtils.jsx
  client/admin/brewUtils/brewUtils.less
  client/admin/brewUtils/stats/stats.jsx
  client/admin/brewUtils/stats/stats.less
  client/admin/notificationUtils/notificationAdd/notificationAdd.less
  client/admin/notificationUtils/notificationLookup/notificationLookup.less
  server/admin.api.js
Labels: cleanup, tweak, UI/UX, 🔍 R0 - Needs first review 👀

#3923 WIP: User Brew Theme Write-in
  client/components/combobox.jsx
  client/homebrew/editor/editor.jsx
  client/homebrew/editor/metadataEditor/metadataEditor.jsx
  client/homebrew/editor/metadataEditor/metadataEditor.less
  client/homebrew/editor/metadataEditor/validations.js
  client/homebrew/navbar/error-navitem.jsx
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/errorPage/errors/errorIndex.js
  client/homebrew/pages/newPage/newPage.jsx
  server/app.js
  server/homebrew.api.js
  server/homebrew.api.spec.js
  shared/helpers.js
Labels: feature, Approved, 🔍 R4 - Fixed! Awaiting re-review⭐

#3984 Extend header nav to skip headers in "top level" pages
  client/homebrew/brewRenderer/headerNav/headerNav.jsx
  client/homebrew/brewRenderer/headerNav/headerNav.less
Labels: P3 - low priority, 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#4043 Move Superscript/Subscript functions into their own module
  .circleci/config.yml
  package-lock.json
  package.json
  shared/naturalcrit/markdown.js
Labels: 🔍 R4 - Fixed! Awaiting re-review⭐

#4058 Change hardbreak to `<br>`
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.less
  client/homebrew/pages/basePages/uiPage/uiPage.less
  shared/naturalcrit/markdown.js
  tests/markdown/definition-lists.test.js
  tests/markdown/hard-breaks.test.js
  themes/V3/5ePHB/style.less
  themes/V3/Blank/style.less
Labels: phb-style, 🔍 R5 - Approved for merge :100:

#4023 Small adjustments to the PHB theme snippets
  themes/V3/5ePHB/style.less
Labels: tweak, UI/UX, ❌ Missing from V3, P2 - minor feature or not urgent, Approved, 🔍 R0 - Needs first review 👀
