Repository naturalcrit/homebrewery, pull requests merged in 2025-01, with the labels that each got.

#3959 Update Docker instructions in support of #1930
  Dockerfile
  README.DOCKER.md
  docker-compose.yml
Labels: 🔍 R0 - Needs first review 👀, documentation

#3972 Error Bar refactor - fixes
  client/components/dialog.jsx
  client/homebrew/brewRenderer/errorBar/errorBar.jsx
  client/homebrew/brewRenderer/errorBar/errorBar.less
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.jsx
Labels: 🔍 R5 - Approved for merge :100:

#3975 Apply fix to clear error.
  client/homebrew/pages/sharePage/sharePage.jsx
Labels: 🔍 R3 - Reviewed - Awaiting Fixes 🔧

#3992 Implement suggested fix for 3448
  shared/naturalcrit/markdown.js
  tests/markdown/variables.test.js
Labels: tweak, 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐

#3908 V4 proposed aligned paragraph tokens
  .circleci/config.yml
  package.json
  shared/naturalcrit/markdown.js
  tests/markdown/paragraph-justification.test.js
  themes/V3/Blank/style.less
Labels: 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐, 🚀 V4

#3977 Ubuntu document upgrade
  install/README.UBUNTU.md
  install/ubuntu/etc/systemd/system/homebrewery.service
  install/ubuntu/install.sh
Labels: documentation, 🔍 R5 - Approved for merge :100:

#4004 Alternate \page{curlies}
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/editor/editor.jsx
Labels: 🔍 R4 - Reviewed - Fixed! Awaiting final review⭐

#4019 upadte notification popup to handle markdown
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.jsx
  client/homebrew/brewRenderer/notificationPopup/notificationPopup.less
Labels: tweak, UI/UX, 🔍 R5 - Approved for merge :100:
