Repository naturalcrit/homebrewery, pull requests merged in 2025-10, with the labels that each got.

#4435 remove custom scrollbar styles
  shared/naturalcrit/codeEditor/codeEditor.less
Labels: tweak, UI/UX, Approved, 🔍 R0 - Needs first review 👀, 🎃 Hacktoberfext

#4438 Fix default save location functionality
  client/homebrew/pages/newPage/newPage.jsx
Labels: bug, P1 - high priority, 🔍 R0 - Needs first review 👀, 🎃 Hacktoberfest

#4436 Add indexes to Mongo schema
  README.md
  server/db.js
  server/homebrew.model.js
Labels: P2 - minor feature or not urgent, 🔍 R5 - Approved for merge :100:, 🎃 Hacktoberfest

#4452 Standardize local storage key names #4119
  client/admin/admin.jsx
  client/components/splitPane/splitPane.jsx
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/toolBar/toolBar.jsx
  client/homebrew/editor/editor.jsx
  client/homebrew/homebrew.jsx
  client/homebrew/navbar/recent.navitem.jsx
  client/homebrew/pages/accountPage/accountPage.jsx
  client/homebrew/pages/basePages/listPage/listPage.jsx
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/newPage/newPage.jsx
  client/homebrew/utils/updateLocalStorage/localStorageKeyMap.js
  client/homebrew/utils/updateLocalStorage/localStorageKeyMap.spec.js
  client/homebrew/utils/updateLocalStorage/updateLocalStorageKeys.js
Labels: cleanup, P2 - minor feature or not urgent, 🔍 R5 - Approved for merge :100:, 🎃 Hacktoberfest

#4453 Add Windows-specific instructions to Docker README
  README.DOCKER.md
Labels: P2 - minor feature or not urgent, 🔍 R5 - Approved for merge :100:, 🎃 Hacktoberfest

#4456 Remove handler function for cursor/renderer page. Use setState directly
  client/homebrew/pages/editPage/editPage.jsx
  client/homebrew/pages/homePage/homePage.jsx
  client/homebrew/pages/newPage/newPage.jsx
Labels: 🔍 R5 - Approved for merge :100:, 🎃 Hacktoberfest

#4455 Permanently enable old local storage key deletion
  client/homebrew/utils/updateLocalStorage/updateLocalStorageKeys.js
Labels: bug, P1 - high priority, 🔍 R0 - Needs first review 👀, 🎃 Hacktoberfest

#4434 Fix dev background
  client/homebrew/brewRenderer/brewRenderer.jsx
  client/homebrew/brewRenderer/brewRenderer.less
  client/homebrew/homebrew.jsx
  client/homebrew/homebrew.less
  client/homebrew/pages/vaultPage/vaultPage.less
  config/default.json
Labels: feature, tweak, 🔍 R3 - Reviewed - Awaiting Fixes 🔧, 🎃 Hacktoberfest

#4447 Applies G-Ambatte's fix for Firefox browser lock.
  themes/V3/Blank/style.less
Labels: 🔍 R1 - Reviewed - Needs Discussion 💬, 🎃 Hacktoberfest
